import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://aia--upgradestg.sandbox.my.salesforce.com/');
  await page.getByLabel('Username').fill('sgopisetty@innominds.com.aia.prod.upgradestg');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Fonteva@446');
  await page.getByRole('button', { name: 'Log In to Sandbox' }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/page/home');
  await page.getByRole('link', { name: 'Contacts' }).click();
  await page.getByRole('button', { name: 'New' }).click();
  await page.getByRole('combobox', { name: 'Prefix' }).click();
  await page.getByPlaceholder('Last Name').fill('testName');
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').fill('testname');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/Contact/003Ek00000ZwTzyIAF/view');
  await expect(page.locator('records-highlights2 lightning-formatted-name')).toBeVisible();
  await expect(page.locator('records-highlights2 lightning-formatted-name')).toBeVisible();
  await page.locator('records-highlights2 lightning-formatted-name').click();
  await expect(page.locator('records-highlights2')).toContainText('testname');
  await page.getByRole('button', { name: 'Join', exact: true }).click();
  await page.getByRole('combobox', { name: 'Membership Type' }).click();
  await page.getByRole('option', { name: 'Architect' }).locator('span').nth(1).click();
  await page.getByRole('combobox', { name: 'Membership Country Assignment' }).click();
  await page.getByRole('option', { name: 'United States' }).click();
  await page.getByLabel('Membership Zip Code Assignment').click();
  await page.getByLabel('Membership Zip Code Assignment').fill('38671');
  await page.getByRole('combobox', { name: 'Career Type' }).click();
  await page.getByRole('option', { name: 'Non profit' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Join License Number').click();
  await page.getByLabel('Join License Number').fill('12345');
  await page.getByRole('combobox', { name: 'Join License Country' }).click();
  await page.getByRole('option', { name: 'United States' }).locator('span').nth(1).click();
  await page.getByRole('combobox', { name: 'Join License State' }).click();
  await page.getByRole('option', { name: 'Alaska' }).locator('span').nth(1).click();
  await page.getByLabel('Join License Date').click();
  await page.getByLabel('Pick a Year').selectOption('2020');
  await page.getByRole('button', { name: '25' }).click();
  await page.getByLabel('Join License Expire Date').click();
  await page.getByLabel('Pick a Year').selectOption('2030');
  await page.getByLabel('-11-27').getByRole('button', { name: '27' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('combobox', { name: 'Subscription Plans' }).click();
  await page.getByRole('option', { name: 'Dues - Payment in Full' }).locator('span').nth(1).click();
  await expect(page.getByRole('button', { name: 'Create sales order' })).toBeVisible();
  await page.getByRole('button', { name: 'Create sales order' }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/OrderApi__Sales_Order__c/a1JEk00000CuYZZMA3/view');
  await expect(page.locator('forcegenerated-highlightspanel_orderapi__sales_order__c___012000000000000aaa___compact___view___recordlayout2')).toContainText('$630.00');
  await page.getByRole('button', { name: 'Ready For Payment' }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/OrderApi__Sales_Order__c/a1JEk00000CuYZZMA3/view');
  await page.getByRole('button', { name: 'Apply Payment' }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/one/one.app#eyJjb21wb25lbnREZWYiOiJvbmU6YWxvaGFQYWdlIiwiYXR0cmlidXRlcyI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9haWEtLXVwZ3JhZGVzdGctLWx0ZS5zYW5kYm94LnZmLmZvcmNlLmNvbS9hcGV4L1BheW1lbnRSb3V0ZXI%2FaWQ9YTFKRWswMDAwMEN1WVpaTUEzIn0sInN0YXRlIjp7fX0%3D');
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().getByRole('button', { name: 'Apply Payment' }).click();
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().getByLabel('Payment Type').selectOption('a2FEk000000HhdFMAS');
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('button').filter({ hasText: 'Apply Payment' }).click();
  
  await expect(page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().locator('.p-HeightObserverProvider')).toBeVisible();
  await expect(page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().getByPlaceholder('1234 1234 1234')).toBeVisible();
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().getByPlaceholder('1234 1234 1234').click();
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().getByPlaceholder('1234 1234 1234').fill('4242 4242 4242 4242');
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().getByPlaceholder('MM / YY').click();
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().getByPlaceholder('MM / YY').fill('12 / 30');
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().getByPlaceholder('CVC').click();
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().locator('iframe[title="Payment Custom Form"]').contentFrame().locator('#paymentElementIframe-0').contentFrame().locator('iframe[name="__privateStripeFrame5494"]').contentFrame().getByPlaceholder('CVC').fill('678');
  await expect(page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().getByRole('button', { name: 'Process Payment' })).toBeVisible();
  await page.locator('iframe[name="vfFrameId_1730865192067"]').contentFrame().getByRole('button', { name: 'Process Payment' }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/OrderApi__Receipt__c/a1EEk000004xB0LMAU/view');
  await expect(page.locator('records-highlights2')).toContainText('0000408253');
  await expect(page.locator('lightning-formatted-text').filter({ hasText: '0000408253' })).toBeVisible();
  await expect(page.locator('records-highlights2')).toContainText('testname');
  await expect(page.locator('records-highlights2')).toContainText('$630.00');
  await expect(page.locator('records-highlights2')).toContainText('000752969');
  await page.getByRole('link', { name: 'testname', exact: true }).click();
  await page.getByRole('link', { name: 'Show All (25)' }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/Contact/003Ek00000ZwTzyIAF/view');
  await expect(page.getByRole('link', { name: 'Memberships (1)' })).toBeVisible();
  await page.getByRole('link', { name: 'Memberships (1)' }).click();
  await expect(page.locator('tbody')).toContainText('Active');
  await expect(page.getByLabel('Status', { exact: true }).locator('a')).toContainText('Active');
  await expect(page.getByText('Active', { exact: true })).toBeVisible();
  await page.getByText('$').click();
  await expect(page.locator('tbody')).toContainText('$630.00');
  await expect(page.locator('formula-output-formula-html')).toContainText('testname');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('gridcell', { name: 'testname' }).getByRole('link').click();
  const page1 = await page1Promise;
  await page1.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/Contact/003Ek00000ZwTzyIAF/view');
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/Contact/003Ek00000ZwTzyIAF/view');
  await page1.getByRole('link', { name: 'Show All (25)' }).click();
  await page.getByRole('link', { name: 'Show All (25)' }).click();

  await page.getByRole('link', { name: 'Sales Orders (1)' }).click();
  await page.goto('https://aia--upgradestg.sandbox.lightning.force.com/lightning/r/Contact/003Ek00000ZwTzyIAF/related/OrderApi__Sales_Orders__r/view');
  await expect(page.getByRole('grid')).toContainText('Closed');
  await expect(page.getByRole('grid')).toContainText('$630.00');
  await expect(page.getByRole('grid')).toContainText('Membership Join');
  await expect(page.getByRole('gridcell', { name: 'Posted' }).locator('span').first()).toBeVisible();
  await expect(page.getByRole('gridcell', { name: 'Posted' }).locator('span').first()).toBeVisible();
  await page.getByRole('gridcell', { name: 'Posted' }).locator('span').first().dblclick();
  await page.getByRole('gridcell', { name: 'Posted' }).locator('span').first().click();
  await page.getByRole('gridcell', { name: 'Posted' }).locator('span').first().click();
  await page.getByRole('gridcell', { name: 'Posted' }).locator('span').first().click();
  await expect(page.getByRole('grid')).toContainText('Posted');
  await page.getByRole('button', { name: 'View profile' }).click();
  await page.getByRole('link', { name: 'Log Out', exact: true }).click();
  await page.goto('https://aia--upgradestg.sandbox.my.salesforce.com/');
});